require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InternsController do

  # This should return the minimal set of attributes required to create a valid
  # Intern. As you add validations to Intern, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "department_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InternsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all interns as @interns" do
      intern = Intern.create! valid_attributes
      get :index, {}, valid_session
      assigns(:interns).should eq([intern])
    end
  end

  describe "GET show" do
    it "assigns the requested intern as @intern" do
      intern = Intern.create! valid_attributes
      get :show, {:id => intern.to_param}, valid_session
      assigns(:intern).should eq(intern)
    end
  end

  describe "GET new" do
    it "assigns a new intern as @intern" do
      get :new, {}, valid_session
      assigns(:intern).should be_a_new(Intern)
    end
  end

  describe "GET edit" do
    it "assigns the requested intern as @intern" do
      intern = Intern.create! valid_attributes
      get :edit, {:id => intern.to_param}, valid_session
      assigns(:intern).should eq(intern)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Intern" do
        expect {
          post :create, {:intern => valid_attributes}, valid_session
        }.to change(Intern, :count).by(1)
      end

      it "assigns a newly created intern as @intern" do
        post :create, {:intern => valid_attributes}, valid_session
        assigns(:intern).should be_a(Intern)
        assigns(:intern).should be_persisted
      end

      it "redirects to the created intern" do
        post :create, {:intern => valid_attributes}, valid_session
        response.should redirect_to(Intern.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved intern as @intern" do
        # Trigger the behavior that occurs when invalid params are submitted
        Intern.any_instance.stub(:save).and_return(false)
        post :create, {:intern => { "department_id" => "invalid value" }}, valid_session
        assigns(:intern).should be_a_new(Intern)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Intern.any_instance.stub(:save).and_return(false)
        post :create, {:intern => { "department_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested intern" do
        intern = Intern.create! valid_attributes
        # Assuming there are no other interns in the database, this
        # specifies that the Intern created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Intern.any_instance.should_receive(:update).with({ "department_id" => "1" })
        put :update, {:id => intern.to_param, :intern => { "department_id" => "1" }}, valid_session
      end

      it "assigns the requested intern as @intern" do
        intern = Intern.create! valid_attributes
        put :update, {:id => intern.to_param, :intern => valid_attributes}, valid_session
        assigns(:intern).should eq(intern)
      end

      it "redirects to the intern" do
        intern = Intern.create! valid_attributes
        put :update, {:id => intern.to_param, :intern => valid_attributes}, valid_session
        response.should redirect_to(intern)
      end
    end

    describe "with invalid params" do
      it "assigns the intern as @intern" do
        intern = Intern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Intern.any_instance.stub(:save).and_return(false)
        put :update, {:id => intern.to_param, :intern => { "department_id" => "invalid value" }}, valid_session
        assigns(:intern).should eq(intern)
      end

      it "re-renders the 'edit' template" do
        intern = Intern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Intern.any_instance.stub(:save).and_return(false)
        put :update, {:id => intern.to_param, :intern => { "department_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested intern" do
      intern = Intern.create! valid_attributes
      expect {
        delete :destroy, {:id => intern.to_param}, valid_session
      }.to change(Intern, :count).by(-1)
    end

    it "redirects to the interns list" do
      intern = Intern.create! valid_attributes
      delete :destroy, {:id => intern.to_param}, valid_session
      response.should redirect_to(interns_url)
    end
  end

end
